=== Atulin/hfyEbook/specs/_schema.json
{
	"$ref": "#/definitions/mySchema",
	"definitions": {
		"mySchema": {
			"type": "object",
			"properties": {
				"patreon": {
					"type": "string",
					"description": "Link to the author's Patreon."
				},
				"title": {
					"type": "string",
					"description": "Used as the book title and as the basis for the output filename."
				},
				"creator": {
					"type": "string",
					"description": "The name of the author. Embedded into output meta-data and used for by-lines."
				},
				"filters": {
					"anyOf": [
						{
							"type": "array",
							"items": {
								"type": "string"
							}
						},
						{
							"type": "object",
							"additionalProperties": {
								"type": "array",
								"items": {
									"type": "string"
								}
							}
						}
					],
					"description": "Names of filters to be applied to each chapter sequentially, or a set of named filter name arrays."
				},
				"filename": {
					"type": "string",
					"description": "Specifies the base name for emitted output files. Omits extension, since that is appended by each output plugin (see below) as appropriate."
				},
				"output": {
					"anyOf": [
						{
							"type": "string"
						},
						{
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					],
					"description": "Used to specify one or more integrations filters that build output files based on the filtered chapter contents."
				},
				"contents": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"byline": {
								"type": "string",
								"description": "If specified, this will add an author byline to this chapter. This can be used to support collected content by various authors with full per-chapter attribution."
							},
							"title": {
								"type": "string",
								"description": "The chapter title. Used to generate headings and when building TOCs."
							},
							"src": {
								"type": "string",
								"description": "The source location of the material for the given chapter. This can be any value appropriate to the chosen input filter."
							},
							"no-preamble-treshold": {
								"type": "number"
							},
							"sw-part-index": {
								"type": "number"
							}
						},
						"required": ["title", "src"],
						"additionalProperties": false
					},
					"description": "Each element of the array is an object describing a chapter."
				},
				"no-preamble-treshold": {
					"type": "number"
				},
				"$schema": {
					"type": "string"
				}
			},
			"required": [
				"title",
				"creator",
				"filters",
				"filename",
				"output",
				"contents",
				"$schema"
			],
			"additionalProperties": false
		}
	},
	"$schema": "http://json-schema.org/draft-07/schema#"
}

=== Atulin/hfyEbook/specs/billy-bob-space-trucker.json
{
	"$schema": "_schema.json",
	"title": "Billy-Bob Space Trucker",
	"creator": "RegalLegalEagle",
	"patreon": "https://www.patreon.com/user?u=2300449",
	"filters": [
		"from-reddit-post",
		"clean-reddit",
		"no-preamble",
		"billy-bob-space-trucker",
		"typography",
		"finalize"
	],
	"filename": "Billy-Bob Space Trucker",
	"output": ["epub", "html", "latex"],
	"contents": [
		{
			"title": "Un",
			"src": "https://www.reddit.com/r/HFY/comments/2gmgmt/oc_billybob_space_trucker/"
		},
		{
			"title": "Deux",
			"src": "https://www.reddit.com/r/HFY/comments/2gpyhg/oc_billybob_space_trucker_chapitre_deux/"
		},
		{
			"title": "Trois",
			"src": "https://www.reddit.com/r/HFY/comments/2gtyod/oc_billybob_space_trucker_chapitre_trois/"
		},
		{
			"title": "Quatre",
			"src": "https://www.reddit.com/r/HFY/comments/2gx4if/oc_billybob_space_trucker_chapitre_quatre/"
		},
		{
			"title": "Cinq",
			"src": "https://www.reddit.com/r/HFY/comments/2gzjqp/oc_billybob_space_trucker_chapitre_cinq/"
		},
		{
			"title": "Six",
			"src": "https://www.reddit.com/r/HFY/comments/2h6q5l/oc_billybob_space_trucker_chapitre_six/"
		},
		{
			"title": "Sept",
			"src": "https://www.reddit.com/r/HFY/comments/2h9uib/oc_billybob_space_trucker_chapitre_sept/"
		},
		{
			"title": "Huit",
			"src": "https://www.reddit.com/r/HFY/comments/2hedb0/oc_billybob_space_trucker_chapitre_huit/"
		},
		{
			"title": "Neuf",
			"src": "https://www.reddit.com/r/HFY/comments/2hhw8o/oc_billybob_chapitre_neuf/"
		},
		{
			"title": "Dix",
			"src": "https://www.reddit.com/r/HFY/comments/2hl3ck/oc_billybob_space_trucker_chapitre_dix/"
		},
		{
			"title": "Onze",
			"src": "https://www.reddit.com/r/HFY/comments/2huhi8/oc_billybob_space_trucker_chapitre_onze/"
		},
		{
			"title": "Douze",
			"src": "https://www.reddit.com/r/HFY/comments/2hxrgl/oc_billybob_space_trucker_chapitre_douze/"
		},
		{
			"title": "Treize",
			"src": "https://www.reddit.com/r/HFY/comments/2i2ccw/oc_billybob_space_trucker_chapitre_treize/"
		},
		{
			"title": "Quatorze",
			"src": "https://www.reddit.com/r/HFY/comments/2i5e51/oc_billybob_space_trucker_chapitre_quatorze/"
		},
		{
			"title": "Quinze",
			"src": "https://www.reddit.com/r/HFY/comments/2ib1vw/oc_billybob_space_trucker_chapitre_quinze/"
		},
		{
			"title": "Seize",
			"src": "https://www.reddit.com/r/HFY/comments/2ii7qr/oc_billybob_space_trucker_chapitre_seize/"
		},
		{
			"title": "Dix-Sept",
			"src": "https://www.reddit.com/r/HFY/comments/2ilmmj/oc_billybob_space_trucker_chapitre_dixsept/"
		},
		{
			"title": "Dix-Huit",
			"src": "https://www.reddit.com/r/HFY/comments/2ipvvp/oc_billybob_space_trucker_chapitre_dixhuit/"
		},
		{
			"title": "Dix-Neuf",
			"src": "https://www.reddit.com/r/HFY/comments/2it62x/oc_billybob_space_trucker_chapitre_dixneuf/"
		},
		{
			"title": "Vingt",
			"src": "https://www.reddit.com/r/HFY/comments/2iwksd/oc_billybob_space_trucker_chapitre_vingt_deux_dix/"
		},
		{
			"title": "Falling from on high",
			"src": "https://www.reddit.com/r/HFY/comments/2iz1qz/oc_falling_from_on_high/"
		},
		{
			"title": "Vingt-Et-Un",
			"src": "https://www.reddit.com/r/HFY/comments/2j61i3/oc_billybob_space_trucker_chapitre_vingt_et_un/"
		},
		{
			"title": "Vingt-Deux",
			"src": "https://www.reddit.com/r/HFY/comments/2j9zl5/oc_billybob_space_trucker_chapitre_vingtdeux/"
		},
		{
			"title": "Vingt-Trois",
			"src": "https://www.reddit.com/r/HFY/comments/2jdfw1/oc_billybob_space_trucker_chapitre_vingttrois/"
		},
		{
			"title": "Vingt-Quatre",
			"src": "https://www.reddit.com/r/HFY/comments/2jgwjn/oc_billybob_space_trucker_chapitre_vingtquatre/"
		},
		{
			"title": "Vingt-Cinc",
			"src": "https://www.reddit.com/r/HFY/comments/2jkn13/oc_billybob_space_trucker_chapitre_vingtcinq/"
		},
		{
			"title": "Vingt-Six",
			"src": "https://www.reddit.com/r/HFY/comments/2juis8/oc_billybob_space_trucker_chapitre_vingtsix/"
		},
		{
			"title": "Vingt-Sept",
			"src": "https://www.reddit.com/r/HFY/comments/2jxpc2/oc_billybob_space_trucker_chapitre_vingtsept/"
		},
		{
			"title": "Vingt-Huit",
			"src": "https://www.reddit.com/r/HFY/comments/2k1ysi/oc_billybob_space_trucker_chapitre_vingthuit/"
		},
		{
			"title": "Vingt-Neuf",
			"src": "https://www.reddit.com/r/HFY/comments/2k5fd1/oc_billybob_space_trucker_chapitre_vingtneuf/"
		},
		{
			"title": "Trente",
			"src": "https://www.reddit.com/r/HFY/comments/2kiuj9/oc_billybob_space_trucker_chapitre_trente/"
		},
		{
			"title": "Trente-Et-Un",
			"src": "https://www.reddit.com/r/HFY/comments/2lwziv/oc_billybob_space_trucker_chapitre_trente_et_un/"
		},
		{
			"title": "Trente-Deux",
			"src": "https://www.reddit.com/r/HFY/comments/2m4uf9/oc_billybob_space_trucker_chapitre_trente_deux/"
		},
		{
			"title": "Trente-Trois",
			"src": "https://www.reddit.com/r/HFY/comments/2mc6ev/oc_billybob_space_trucker_chapitre_trentetrois/"
		},
		{
			"title": "Trente-Quatre",
			"src": "https://www.reddit.com/r/HFY/comments/2mmgmx/oc_billybob_space_trucker_chapitre_trentequatre/"
		},
		{
			"title": "Trente-Cinq première partie",
			"src": "https://www.reddit.com/r/HFY/comments/2mui7w/oc_billybob_space_trucker_chapitre_trentecinq/"
		},
		{
			"title": "Trente-Cinq deuxième partie",
			"src": "https://www.reddit.com/r/HFY/comments/2obnvi/ocbillybob_space_trucker_chapitre_trentecinq/"
		},
		{
			"title": "La Fin",
			"src": "https://www.reddit.com/r/HFY/comments/2oflhg/oc_billybob_space_trucker_la_fin/"
		}
	]
}

=== Atulin/hfyEbook/specs/clint-stone-freedom.json
{
	"$schema": "_schema.json",
	"title": "Chronicles of Clint Stone\nPart 1: Freedom",
	"creator": "someguynamedted",
	"filters": [
		"from-reddit-post",
		"clean-reddit",
		"no-preamble",
		"clint-stone-freedom",
		"typography",
		"finalize"
	],
	"filename": "Chronicles of Clint Stone 1 - Freedom",
	"output": ["epub", "latex", "html"],
	"contents": [
		{
			"title": "Freedom",
			"src": "https://www.reddit.com/r/HFY/comments/25c0k6/oc_clint_stone_freedom/"
		},
		{
			"title": "Susan",
			"src": "https://www.reddit.com/r/HFY/comments/25nr97/oc_clint_stone_susan/"
		},
		{
			"title": "Undone",
			"src": "https://www.reddit.com/r/HFY/comments/26f9ij/oc_clint_stone_undone/"
		},
		{
			"title": "Stranger",
			"src": "https://www.reddit.com/r/HFY/comments/266lbi/oc_clint_stone_stranger/"
		},
		{
			"title": "Bottoms Up",
			"src": "https://www.reddit.com/r/HFY/comments/25e7ga/oc_clint_stone_bottoms_up/"
		},
		{
			"title": "The Feast",
			"src": "https://www.reddit.com/r/HFY/comments/25otea/oc_clint_stone_the_feast/"
		},
		{
			"title": "Greetings",
			"src": "https://www.reddit.com/r/HFY/comments/26cqap/oc_clint_stone_greetings/"
		},
		{
			"title": "Unarmed",
			"src": "https://www.reddit.com/r/HFY/comments/25lq17/oc_clint_stone_unarmed/"
		},
		{
			"title": "Fireproof",
			"src": "https://www.reddit.com/r/HFY/comments/25tllp/ocfire_clint_stone_fireproof/"
		},
		{
			"title": "Children",
			"src": "https://www.reddit.com/r/HFY/comments/25uaw8/oc_clint_stone_children/"
		},
		{
			"title": "Retribution",
			"src": "https://www.reddit.com/r/HFY/comments/25wwf9/oc_clint_stone_retribution/"
		},
		{
			"title": "Lost",
			"src": "https://www.reddit.com/r/HFY/comments/26his6/oc_clint_stone_lost/"
		},
		{
			"title": "Search",
			"src": "https://www.reddit.com/r/HFY/comments/26j454/oc_clint_stone_search/"
		},
		{
			"title": "Intrusion",
			"src": "https://www.reddit.com/r/HFY/comments/26kn1u/oc_clint_stone_intrusion/"
		},
		{
			"title": "Trapped",
			"src": "https://www.reddit.com/r/HFY/comments/26nw51/oc_clint_stone_trapped/"
		},
		{
			"title": "Quest",
			"src": "https://www.reddit.com/r/HFY/comments/26qzks/oc_clint_stone_quest/"
		},
		{
			"title": "Whole",
			"src": "https://www.reddit.com/r/HFY/comments/26u1vu/oc_clint_stone_whole/"
		},
		{
			"title": "Hand of War",
			"src": "https://www.reddit.com/r/HFY/comments/26uol0/oc_clint_stone_hand_of_war/"
		},
		{
			"title": "Owed",
			"src": "https://www.reddit.com/r/HFY/comments/270hjq/oc_clint_stone_owed/"
		},
		{
			"title": "Darling",
			"src": "https://www.reddit.com/r/HFY/comments/27306a/oc_clint_stone_darling/"
		},
		{
			"title": "Freed",
			"src": "https://www.reddit.com/r/HFY/comments/279ade/oc_clint_stone_freed/"
		},
		{
			"title": "Lost Tales",
			"src": "https://www.reddit.com/r/HFY/comments/25qz77/oc_clint_stone_lost_tales/"
		}
	]
}

=== Atulin/hfyEbook/specs/jverse-deathworld-origins.json
{
	"$schema": "_schema.json",
	"title": "Deathworld Origins",
	"creator": "captainmeta4",
	"filters": ["from-reddit-post", "clean-reddit", "jverse-do", "typography", "finalize"],
	"filename": "Deathworld Origins",
	"output": ["epub", "latex", "html"],
	"contents": [
		{
			"title": "Chapter I",
			"src": "https://www.reddit.com/r/HFY/comments/6n8o20/jverse_deathworld_origins_chapter_i/"
		},
		{
			"title": "Chapter II",
			"src": "https://www.reddit.com/r/HFY/comments/6nfccr/jverse_deathworld_origins_chapter_ii/"
		},
		{
			"title": "Chapter III",
			"src": "https://www.reddit.com/r/HFY/comments/6nlp4x/jverse_deathworld_origins_chapter_iii/"
		},
		{
			"title": "Chapter IV",
			"src": "https://www.reddit.com/r/HFY/comments/6ns9x0/jverse_deathworld_origins_chapter_iv/"
		},
		{
			"title": "Chapter V",
			"src": "https://www.reddit.com/r/HFY/comments/6nzxv6/jverse_deathworld_origins_chapter_v/"
		},
		{
			"title": "Chapter VI",
			"src": "https://www.reddit.com/r/HFY/comments/6o7lds/jverse_deathworld_origins_chapter_vi/"
		},
		{
			"title": "Chapter VII",
			"src": "https://www.reddit.com/r/HFY/comments/6ofhj5/jverse_deathworld_origins_chapter_vii/"
		},
		{
			"title": "Chapter VIII",
			"src": "https://www.reddit.com/r/HFY/comments/6on7ye/jverse_deathworld_origins_chapter_viii/"
		}
	]
}
